- name: "Copy directories to volumes"
  shell: |
    docker cp /tmp/{{conf_file.value.directory}} tmpvol:/{{ item }}
  with_items: "{{ conf_file.value.volumes }}"
  when: "'directory' in conf_file.value"

- name: "Copy config files to volumes"
  shell: |
    docker cp /tmp/{{conf_file.key}} tmpvol:/{{ item }}
  with_items: "{{ conf_file.value.volumes }}"
  when: "'directory' not in conf_file.value"
