- name: "check if {{ item }} exists"
  command: docker volume inspect {{ item }}
  register: myvolume_exists
  ignore_errors: True

- name: "create {{ item }}"
  command: docker volume create --name {{ item }}
  when: myvolume_exists|failed

